### PR TITLE
MP JWT 1.2 TCK results for 4.1 certification

### PR DESCRIPTION
**Pull request by teddyjtorres**

### CODE REVIEW

**Review by mbroz2 — APPROVED** [review]

**Review by Emily-Jiang — COMMENTED** [review]
@teddyjtorres @mbroz2 please don't update the current TCK result, which was used for ballot when releasing MP 4.1
As mentioned on the call, please put the TCKResult under microprofile/4.1/21.0.0.9/mpjwt...

**Comment by Emily-Jiang** [comment]
please revert your commit @teddyjtorres @mbroz2

**Comment by teddyjtorres** [comment]
I created https://github.com/OpenLiberty/certifications/pull/129 to put the file in the indicated location.

**Comment by Emily-Jiang** [comment]
Thank you @teddyjtorres !

**Pull request merged**
