### PR TITLE
Adding EE 9.1 GM Certification Records

### PR DESCRIPTION
**Pull request by mbroz2**
- Updating to use OL logomark
- Results for Java 8/11/17 and WebProfile/Platform

Looks good on draft site: https://certifications-draft-openlibertyio.mybluemix.net/certifications/
image

Only thing I've noticed is that how/what we display for Java 8 results differs from 11 and 17 (which have more detail regarding the SE version).  However, I believe it's what we've done in the past so no immediate concerns.

### CODE REVIEW

**Review by jhanders34 — CHANGES_REQUESTED** [review]
The Java 11 and Java 17 Web Profile results include XML Binding TCK results.  XML Binding is an optional specification for Platform, but is not related to web profile at all.  It can be removed from those two results.

**Comment by mbroz2** [comment]
@brideck since you made the branch in your fork and not this repo, can you make that update.

**Comment by brideck** [comment]
Good call on the Java reporting difference.  I should be able to update the Java 8 one to match the quality of what we report elsewhere.  The existing text had just been carried forward from previous certifications.

I'll also yank the XML Binding info from the Web Profile pages per Jared's comment.

**Comment by brideck** [comment]
@jhanders34 @mbroz2 Updates have been made.  Please take a look at the changes to see if they match your expectations.

**Review by jhanders34 — APPROVED** [review]

**Comment by brideck** [comment]
Updated version on the draft site looks good to me, too.

**Pull request merged**
